"""Offline place search, backed by the GeoNames SQLite index.

Birth data is entered by place name, never by coordinates -- nobody knows the
latitude of the village they were born in. This module turns "Madurai" or
"மதுரை" into coordinates *and* an IANA timezone, which is everything
:class:`~jyotish.core.birthdata.BirthData` needs.

Build the index first::

    python scripts/build_places_db.py

Data (c) GeoNames, CC BY 4.0 -- https://www.geonames.org/
"""

from __future__ import annotations

import os
import sqlite3
import threading
import unicodedata
from dataclasses import dataclass
from pathlib import Path

#: Bumped whenever the index layout or the key-folding rule changes. The builder
#: stamps it; `_connect` refuses a mismatch rather than silently searching keys
#: that were generated by different rules, which would look like missing places.
SCHEMA_VERSION = 2

DB_PATH = Path(
    os.environ.get(
        "ASTROAPP_PLACES_DB",
        Path(__file__).resolve().parents[3].parent / "data" / "places.sqlite",
    )
)

_lock = threading.RLock()
_connection: sqlite3.Connection | None = None

_COLUMNS = (
    "geonameid, name, ascii_name, admin1, country_code, country_name, "
    "latitude, longitude, timezone, population, feature_code"
)


class PlacesDatabaseMissing(RuntimeError):
    """Raised when the index has not been built yet, or is out of date."""


def fold_name(text: str) -> str:
    """Lowercase, and strip diacritics from Latin letters only.

    ``Hosūr`` -> ``hosur``, ``Zürich`` -> ``zurich``, ``São Paulo`` -> ``sao paulo``.

    This is what makes a place findable by the name the app *displays* for it.
    ``search_key`` is built from GeoNames' ``ascii_name``, but ``display_name``
    renders the ``name`` column, which carries diacritics -- so feeding a printed
    result straight back into the search returned nothing for 60.7% of Tamil Nadu
    places. Worse, GeoNames romanises German umlauts (``Zürich`` -> ``Zuerich``),
    so that city matched *neither* spelling.

    The Latin-only restriction is essential, not fussiness. Tamil vowel signs are
    Unicode combining marks too: மதுரை is ம + த + ◌ு + ர + ◌ை, and blindly
    stripping combining characters after NFD would turn it into மதரை -- a
    different word. So a mark is dropped only when it modifies an ASCII letter.

    Must stay identical in the builder and the query path; they import this one
    function precisely because divergence would silently match nothing.
    """
    out: list[str] = []
    for ch in unicodedata.normalize("NFD", text.lower()):
        if unicodedata.combining(ch) and out and out[-1].isascii():
            continue
        out.append(ch)
    return unicodedata.normalize("NFC", "".join(out))


@dataclass(frozen=True)
class Place:
    """A populated place from GeoNames."""

    geonameid: int
    name: str
    ascii_name: str
    admin1: str
    country_code: str
    country_name: str
    latitude: float
    longitude: float
    timezone: str
    population: int
    feature_code: str

    @property
    def display_name(self) -> str:
        """'Madurai, Tamil Nadu, India'."""
        parts = [self.name]
        if self.admin1 and self.admin1 != self.name:
            parts.append(self.admin1)
        if self.country_name:
            parts.append(self.country_name)
        return ", ".join(parts)


def _connect() -> sqlite3.Connection:
    global _connection
    with _lock:
        if _connection is None:
            if not DB_PATH.exists():
                raise PlacesDatabaseMissing(
                    f"Place index not found at {DB_PATH}.\n"
                    "Build it once with:  python scripts/build_places_db.py"
                )
            _connection = sqlite3.connect(
                f"file:{DB_PATH}?mode=ro", uri=True, check_same_thread=False
            )
            _connection.row_factory = sqlite3.Row
            _check_schema_version(_connection)
        return _connection


def _check_schema_version(con: sqlite3.Connection) -> None:
    """Refuse an index built by a different version of the builder.

    A stale index does not fail loudly on its own -- it just stops matching
    certain names, which looks like missing data rather than a build problem.
    """
    try:
        row = con.execute("SELECT value FROM meta WHERE key = 'schema_version'").fetchone()
        found = int(row[0]) if row else 0
    except sqlite3.Error:
        found = 0

    if found != SCHEMA_VERSION:
        raise PlacesDatabaseMissing(
            f"Place index at {DB_PATH} is version {found}, but this code expects "
            f"{SCHEMA_VERSION}.\nRebuild it:  python scripts/build_places_db.py"
        )


def _to_place(row: sqlite3.Row) -> Place:
    return Place(
        geonameid=row["geonameid"],
        name=row["name"],
        ascii_name=row["ascii_name"],
        admin1=row["admin1"] or "",
        country_code=row["country_code"] or "",
        country_name=row["country_name"] or "",
        latitude=row["latitude"],
        longitude=row["longitude"],
        timezone=row["timezone"],
        population=row["population"],
        feature_code=row["feature_code"] or "",
    )


def _prefix_range(prefix: str) -> tuple[str, str]:
    """Half-open ``[lo, hi)`` bounds matching every key starting with ``prefix``.

    This exists instead of ``LIKE 'prefix%'`` for one reason: LIKE cannot use
    our index. SQLite only applies its LIKE optimisation when the column has a
    NOCASE collation (ours is BINARY, because the keys are already lowercased at
    build time), and an ``ESCAPE`` clause disables the optimisation outright.
    The planner therefore fell back to walking ``idx_population`` end to end --
    786,101 rows per query, measured at 1707 ms for "Madurai", and *rising* with
    query length so the final keystroke of a type-ahead was always the slowest.

    A range predicate on the same BINARY index is an ordinary b-tree seek:
    0.4 ms for the identical result set. It is also exactly equivalent here,
    because both the stored keys and the query are lowercased with Python's
    ``str.lower``, and ``%`` and ``_`` are literals in a range comparison rather
    than wildcards -- so no escaping is needed at all.
    """
    last = ord(prefix[-1])
    if last < 0x10FFFF:
        return prefix, prefix[:-1] + chr(last + 1)

    # The final code point cannot be incremented, so carry leftwards. A query
    # made entirely of U+10FFFF has no representable upper bound; returning ""
    # yields no rows, which is also the true answer, since no place name is
    # spelled out of unassigned private-use code points.
    head = prefix.rstrip(chr(0x10FFFF))
    if not head:
        return prefix, ""
    return prefix, head[:-1] + chr(ord(head[-1]) + 1)


#: Prefix-match count above which walking the population index beats seeking the
#: key range and sorting it. The two plans have opposite strengths and each is
#: catastrophic in the other's regime, so the choice is made per query.
#:
#: Measured crossover on the 786,101-row index is ~5,900 matches; both plans cost
#: about 36 ms there, which is the worst case for any query. Away from it they
#: diverge fast: "madurai" (6 matches) is 0.1 ms by range and 807 ms by
#: population walk, while "m" (64,346 matches) is 0.3 ms by walk and 254 ms by
#: range.
_DENSE_PREFIX_MATCHES = 6000


def _prefix_is_dense(con: sqlite3.Connection, lo: str, hi: str) -> bool:
    """How many places share this prefix? Cheap: the count is index-covered.

    Measured at 0.03-1.9 ms across every prefix length, which is negligible
    against the 250 ms it saves on a one-letter query.
    """
    n = con.execute(
        "SELECT COUNT(*) FROM places WHERE search_key >= ? AND search_key < ?",
        (lo, hi),
    ).fetchone()[0]
    return n >= _DENSE_PREFIX_MATCHES


def _name_prefix_sql(p_cols: str, cc_sql: str, dense: bool) -> str:
    """The name-prefix query, in whichever of the two plans suits this prefix."""
    if dense:
        # Many matches: walk the population index in order and stop at LIMIT.
        # A match turns up every few rows, so the scan exits almost immediately.
        # INDEXED BY is required -- left to itself the planner picks the key
        # range here and then sorts sixty thousand rows to return forty.
        # `dense` is only ever true when there is no country filter, so cc_sql
        # is empty and does not need splicing in.
        return (f"SELECT {p_cols} FROM places p INDEXED BY idx_population "
                "WHERE p.search_key >= ? AND p.search_key < ? "
                "ORDER BY p.population DESC LIMIT ?")
    # Few matches: seek the key range and sort it. The sort is over a handful of
    # rows, and this is the only plan that terminates quickly on a rare name.
    return (f"SELECT {p_cols} FROM places p "
            f"WHERE p.search_key >= ? AND p.search_key < ?{cc_sql} "
            "ORDER BY p.population DESC LIMIT ?")


def search(query: str, limit: int = 10, country: str | None = None) -> list[Place]:
    """Search places by name, best match first.

    Results are ranked in four tiers -- exact name, exact alternate name,
    name prefix, alternate-name prefix -- and by population within each tier.

    The tiering is the important part. A bare "Chennai" must return the city of
    four million ahead of every minor place whose name merely begins with the
    same letters, and sorting by population alone would not do that: a hamlet
    named exactly "Chennai" should still lose to the city, but a place called
    "Chennaimalai" should never outrank an exact hit.

    Tamil script works through the alternate-name tiers, which is why they are
    interleaved with the Latin ones rather than appended after them.

    Args:
        query: place name, in Latin or Tamil script.
        limit: maximum results.
        country: optional ISO country code filter, e.g. ``"IN"``.
    """
    q = query.strip()
    if not q:
        return []

    con = _connect()
    # Fold the query the same way the builder folded the keys, so a user can
    # paste back the accented name the app just printed at them.
    key = fold_name(q)
    lo, hi = _prefix_range(key)
    dense = country is None and _prefix_is_dense(con, lo, hi)

    p_cols = ", ".join(f"p.{c}" for c in _COLUMNS.split(", "))
    cc_sql = " AND p.country_code = ?" if country else ""
    cc_args: tuple = (country,) if country else ()

    found: dict[int, tuple[int, Place]] = {}

    def collect(rank: int, sql: str, args: tuple) -> None:
        for row in con.execute(sql, args):
            place = _to_place(row)
            # The first tier to claim a place wins; never demote it later.
            found.setdefault(place.geonameid, (rank, place))

    # Rank is by *exactness*, not by which column matched. A primary-name hit
    # and an alternate-name hit are equally exact, so they share rank 0 and are
    # separated by population. Without this, searching "Trichy" returns a
    # population-zero hamlet named exactly Trichy ahead of Tiruchirappalli, the
    # city of a million that the name actually refers to.
    queries = (
        # Exact romanised name.
        (0, f"SELECT {p_cols} FROM places p WHERE p.search_key = ?{cc_sql} "
            "ORDER BY p.population DESC LIMIT ?", (key,)),
        # Exact alternate name -- this is how Tamil script matches.
        (0, f"SELECT {p_cols} FROM place_names n JOIN places p "
            f"ON p.geonameid = n.geonameid WHERE n.name_key = ?{cc_sql} "
            "ORDER BY p.population DESC LIMIT ?", (key,)),
        # Name prefix ("Madu" -> "Madurai"). Two plans, chosen by density above.
        (1, _name_prefix_sql(p_cols, cc_sql, dense), (lo, hi)),
        # Alternate-name prefix, for partial Tamil input.
        #
        # The range predicate is on place_names, so SQLite drives the join from
        # that table -- 1,824 rows -- instead of scanning all 786,101 places and
        # probing the small table once per row, which is what it did before.
        (1, f"SELECT {p_cols} FROM place_names n JOIN places p "
            f"ON p.geonameid = n.geonameid "
            f"WHERE n.name_key >= ? AND n.name_key < ?{cc_sql} "
            "ORDER BY p.population DESC LIMIT ?", (lo, hi)),
    )

    for rank, sql, args in queries:
        collect(rank, sql, (*args, *cc_args, limit * 4))

    # Demote places GeoNames records with no population by one tier.
    #
    # Village-level coverage is deliberate -- most Tamil birth places are small
    # -- so unpopulated entries must stay findable, and a village with a unique
    # name still ranks first because nothing competes with it. But without this,
    # typing "Madu" returns a population-zero hamlet ahead of Madurai, because
    # an exact match on a hamlet outranks a prefix match on a city of 1.4
    # million. Demoting by exactly one tier makes them tie, and population
    # settles it.
    def sort_key(entry: tuple[int, Place]) -> tuple[int, int]:
        rank, place = entry
        return (rank + (1 if place.population == 0 else 0), -place.population)

    return [place for _rank, place in sorted(found.values(), key=sort_key)[:limit]]


def get(geonameid: int) -> Place | None:
    """Fetch one place by its GeoNames id."""
    row = _connect().execute(
        f"SELECT {_COLUMNS} FROM places WHERE geonameid = ?", (geonameid,)
    ).fetchone()
    return _to_place(row) if row else None


def count() -> int:
    """Number of indexed places. Useful as a build sanity check."""
    return _connect().execute("SELECT COUNT(*) FROM places").fetchone()[0]
